[package]
name = "httpproxy"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4"
regex = "1.10.5"
axum = "0.7"
tower = "0.4"
hyper-util = "0.1"
tracing = "0.1"
derivative = "2.2"
anycache = "1.0.1"
lazy_static = "1.5"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tracing-subscriber = { version="0.3", features=["env-filter"] }
hyper = { version="1.4", features= ["client"] }
tokio = { version = "1", features = ["full"] }