bind_addr: 0.0.0.0
bind_port: 3000
users:
#- username: admin
#  password: admin
#- username: user
#  password: user
default_allow: false
allowed:
- timespec: "* * * * *"
  regex: huasing.*
- timespec: "* 2 * * *"
  regex: a2.*
- timespec: "* 3 * * *"
  regex: a3.*
- timespec: "* 8 * * *"
  regex: google
blocked:
- timespec: "* * * * *"
  regex: r1.*
- timespec: "* 2 * * *"
  regex: r2.*
- timespec: "* 3 * * *"
  regex: r3.*
- timespec: "* 4 * * *"
  regex: r4.*
